# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') { 'postgresql:///disclosure-alert_development' } %>

test:
  <<: *default
  adapter: postgresql
  database: disclosure-alert_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') { 'postgresql:///disclosure-alert_production' } %>
